@startuml cross platform B/L transfer
activate platformA
platformA -> platformA: sign the ebl envelope
platformA -> platformB: PUT /v1/transferblock
activate platformB
platformB -> platformB: verify signature and process ebl envelope
platformB -> platformB: sign response message
platformA <-- platformB: send signed response message
deactivate platformB
platformA -> platformA: verify response signature
@enduml
