version: '3.5'
services:
  dcsa-ec-service:
    build:
      .
    volumes:
      - ./test-certificates:/test-certificates:ro
    ports:
      - 8443:8443
    environment:
      - "db_hostname=dcsa-ec-registry-test-db"
      - "SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}"
      - "SPRING_DATASOURCE_PASSWORD=9c072fe8-c59c-11ea-b8d1-7b6577e9f3f5"
      - "ROOT_LOG_LEVEL=${ROOT_LOG_LEVEL:-INFO}"
      - "DCSA_LOG_LEVEL=${DCSA_LOG_LEVEL:-INFO}"
    logging:
      options:
        max-file: '10'
        max-size: 200k
  dcsa-ec-registry-test-db:
    container_name: ec_registry_db
    environment:
      POSTGRES_PASSWORD: "9c072fe8-c59c-11ea-b8d1-7b6577e9f3f5"
    build:
      datamodel/
    ports:
      - 5432:5432

