
dcsa:
  specification:
    version: 0.0.1

spring:
  application:
    name: DCSA-Endorcement-Chain
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${db_hostname}/tdt_registry
    username: tdt_db_owner
    hikari:
      schema: public
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate.ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dcsa.eu.auth0.com/
  profiles:
    active: nosecurity
    group:
      dev: nosecurity, logsql, localdb
      test: nosecurity, logsql, localdb
      prod: default

server:
  ssl:
    key-store: classpath:certificates/springboot-https.p12
    key-store-password: your_key-store_password
    key-store-type: pkcs12
    key-alias: springboot-https
  port: ${PORT:8443}
  servlet.context-path: /v1
  error:
    include-binding-errors: on_param
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include: "health"

logging:
  level:
    root: ${ROOT_LOG_LEVEL:INFO}
    org:
      springframework: ${SPRING_LOG_LEVEL:INFO}
      dcsa: ${DCSA_LOG_LEVEL:INFO}

---
# A profile for disabling security
spring:
  security:
    keystorePassword: dcsa-pass
    keystoreLocation: certificates/dcsa-jwk.jks
    jws:
        key-id: dcsa-kid
    verification:
      keystoreLocation: certificates/dcsa-jwk-verify.jks
      keystorePassword: dcsa-pass
      jws:
        key-id: dcsa-kid
  config:
    activate:
      on-profile: nosecurity

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration

---
# A profile for connecting to a local database and with local
spring:
  config:
    activate:
      on-profile: localdb

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${db_hostname:localhost}/tdt_registry
    username: tdt_db_owner
    password: 9c072fe8-c59c-11ea-b8d1-7b6577e9f3f5
  jpa:
    show-sql: true

---
# A profile for logging the sql generated by jpa
spring:
  config:
    activate:
      on-profile: logsql

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
