
dcsa:
  specification:
    version: 0.0.1

spring:
  application:
    name: DCSA-Endorcement-Chain
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${db_hostname}/dcsa_ec_registry
    username: dcsa_db_owner
    hikari:
      schema: ec_registry
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: validate
  security:
    keystorePassword: dcsa-pass
    keystoreLocation: ${KEYSTORE_LOCATION:test-certificates/dcsa-jwk.jks}
    jws:
      key-id: ${JWS_KEY_ID:dcsa-kid}
    verification:
      keystoreLocation: ${KEYSTORE_VERIFICATION_LOCATION:test-certificates/dcsa-jwk-verify.jks}
      keystorePassword: dcsa-pass
      jws:
        key-id: dcsa-kid
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dcsa.eu.auth0.com/
  profiles:
    active: nosecurity
    group:
      dev: nosecurity, logsql, localdb
      test: nosecurity, logsql, localdb
      prod: default

server:
  ssl:
    key-store: ${TLS_KEYSTORE:test-certificates/springboot-https.p12}
    key-store-password: ${TLS_KEYSTORE_PASSWORD:your_key-store_password}
    key-store-type: pkcs12
    key-alias: springboot-https
  port: ${PORT:8443}
  hostname: ${HOSTNAME:localhost}
  servlet.context-path: /v1
  error:
    include-binding-errors: on_param
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include: "health"

logging:
  level:
    root: ${ROOT_LOG_LEVEL:INFO}
    org:
      springframework: ${SPRING_LOG_LEVEL:INFO}
      dcsa: ${DCSA_LOG_LEVEL:INFO}

---
# A profile for disabling security
spring:
  config:
    activate:
      on-profile: nosecurity

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration

---
# A profile for connecting to a local database and with local
spring:
  config:
    activate:
      on-profile: localdb

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${db_hostname}/dcsa_ec_registry
    username: dcsa_db_owner
    password: 9c072fe8-c59c-11ea-b8d1-7b6577e9f3f5
  jpa:
    show-sql: true

---
# A profile for logging the sql generated by jpa
spring:
  config:
    activate:
      on-profile: logsql

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
---
spring:
  config:
    activate:
      on-profile: nosslverification

dcsa:
  client:
    tlsVerification: false
